// ── Documentation Generator ──
// Generates JSDoc documentation from code, with AI fallback

interface ApiCheckResult {
  available: boolean;
}

let apiAvailableCache: ApiCheckResult | null = null;

async function checkApiAvailable(): Promise<boolean> {
  if (apiAvailableCache !== null) return apiAvailableCache.available;
  try {
    const res = await fetch("/api/generate", { method: "GET" });
    const data = await res.json();
    apiAvailableCache = { available: !!(data.ok) };
    return apiAvailableCache.available;
  } catch {
    apiAvailableCache = { available: false };
    return false;
  }
}

/**
 * Generate JSDoc documentation for given code.
 */
export async function generateDocs(code: string, language: string): Promise<string> {
  const isApiAvailable = await checkApiAvailable();

  if (isApiAvailable) {
    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          input: `Generate JSDoc documentation comments for the following ${language} code. Only output the documentation with the original code, fully annotated:\n\n${code}`,
        }),
      });
      const data = await res.json();
      if (res.ok && data.generated_text) {
        return data.generated_text;
      }
    } catch {
      // Fall through to regex-based extraction
    }
  }

  // Regex-based extraction fallback
  return generateDocsFromRegex(code, language);
}

/**
 * Extract and generate JSDoc templates using regex patterns.
 */
function generateDocsFromRegex(code: string, language: string): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Auto-generated documentation for ${language}`);
  lines.push(` * Generated by CodeBeing`);
  lines.push(` * @module ${language}-module`);
  lines.push(` */`);
  lines.push("");

  // Extract function signatures
  const funcRegex = /((?:function|const|let|var|async\s+function|export\s+(?:default\s+)?function|export\s+(?:const|let|var))\s+\w+\s*[\(<])/g;
  const funcMatches = [...code.matchAll(funcRegex)];

  for (const match of funcMatches) {
    const signature = match[0];
    const funcName = signature.match(/(\w+)\s*[\(<]/)?.[1] || "anonymous";

    // Extract parameters
    const paramRegex = /\(([^)]*)\)/;
    const paramMatch = signature.match(paramRegex) || match.index !== undefined
      ? code.slice(match.index).match(/\(([^)]*)\)/)
      : null;
    const paramString = paramMatch ? paramMatch[1] : "";
    const params = paramString
      .split(",")
      .map((p) => p.trim())
      .filter(Boolean);

    lines.push(`/**`);
    lines.push(` * ${capitalizeFirst(funcName)} - ${getFunctionDescription(funcName)}`);
    lines.push(` *`);
    if (params.length > 0) {
      for (const param of params) {
        const paramName = param.replace(/=.*$/, "").replace(/:\s*\w+.*$/, "").trim();
        if (paramName) {
          lines.push(` * @param {*} ${paramName} - TODO: describe ${paramName}`);
        }
      }
    }
    lines.push(` * @returns {*} TODO: describe return value`);
    lines.push(` *`);
    lines.push(` * @example`);
    lines.push(` * ${funcName}(${params.length > 0 ? "/* params */" : ""})`);
    lines.push(` */`);
    lines.push("");
  }

  // Extract class definitions
  const classRegex = /class\s+(\w+)/g;
  const classMatches = [...code.matchAll(classRegex)];

  for (const match of classMatches) {
    const className = match[1];
    lines.push(`/**`);
    lines.push(` * ${capitalizeFirst(className)} class`);
    lines.push(` * @class`);
    lines.push(` *`);
    lines.push(` * @description`);
    lines.push(` * TODO: Add class description`);
    lines.push(` *`);
    lines.push(` * @example`);
    lines.push(` * const instance = new ${className}();`);
    lines.push(` */`);
    lines.push("");
  }

  // Extract interface/type definitions
  const interfaceRegex = /(?:interface|type)\s+(\w+)/g;
  const interfaceMatches = [...code.matchAll(interfaceRegex)];

  for (const match of interfaceMatches) {
    const typeName = match[1];
    lines.push(`/**`);
    lines.push(` * ${typeName} type definition`);
    lines.push(` *`);
    lines.push(` * @typedef {Object} ${typeName}`);
    lines.push(` * @property {*} property1 - TODO: describe property`);
    lines.push(` */`);
    lines.push("");
  }

  if (funcMatches.length === 0 && classMatches.length === 0 && interfaceMatches.length === 0) {
    lines.push("// No documented functions, classes, or types found.");
    lines.push("// The code may use patterns not supported by the regex extractor.");
    lines.push("// Consider using the AI-powered documentation generator when online.");
  }

  return lines.join("\n");
}

/**
 * Export documentation as a Markdown string.
 */
export function exportAsMarkdown(docs: string, code: string, language: string): string {
  const lines: string[] = [];
  lines.push(`# Code Documentation`);
  lines.push("");
  lines.push(`> Generated by [CodeBeing](https://codebeing.vercel.app)`);
  lines.push(`> Language: ${capitalizeFirst(language)}`);
  lines.push(`> Date: ${new Date().toLocaleDateString()}`);
  lines.push("");
  lines.push(`---`);
  lines.push("");
  lines.push(`## Documentation`);
  lines.push("");
  lines.push("```" + getLanguageTag(language));
  lines.push(docs);
  lines.push("```");
  lines.push("");
  lines.push(`---`);
  lines.push("");
  lines.push(`## Original Code`);
  lines.push("");
  lines.push("```" + getLanguageTag(language));
  lines.push(code);
  lines.push("```");

  return lines.join("\n");
}

/**
 * Trigger a file download of the given content.
 */
export function downloadMarkdown(content: string, filename: string = "docs.md"): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function capitalizeFirst(str: string): string {
  if (!str) return str;
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function getFunctionDescription(name: string): string {
  const descriptions: Record<string, string> = {
    get: "Retrieves a value",
    set: "Sets a value",
    add: "Adds an item",
    remove: "Removes an item",
    delete: "Deletes an item",
    create: "Creates a new instance",
    update: "Updates an existing item",
    fetch: "Fetches data from a source",
    render: "Renders a component or view",
    handle: "Handles an event or action",
    init: "Initializes the module",
    parse: "Parses input data",
    format: "Formats data for output",
    validate: "Validates input data",
    transform: "Transforms data structure",
    compute: "Computes a result",
    calculate: "Calculates a value",
    process: "Processes data",
    sort: "Sorts a collection",
    filter: "Filters items based on criteria",
    map: "Maps items to new values",
    reduce: "Reduces collection to single value",
    find: "Finds an item in collection",
    search: "Searches for matching items",
    merge: "Merges multiple sources",
    clone: "Creates a copy",
    subscribe: "Subscribes to events",
    unsubscribe: "Unsubscribes from events",
    emit: "Emits an event",
    listen: "Listens for events",
    connect: "Establishes a connection",
    disconnect: "Closes a connection",
  };

  for (const [prefix, desc] of Object.entries(descriptions)) {
    if (name.toLowerCase().startsWith(prefix) && name.toLowerCase() !== prefix) {
      return desc;
    }
  }

  return `TODO: describe what this function does`;
}

function getLanguageTag(language: string): string {
  const map: Record<string, string> = {
    python: "python",
    javascript: "javascript",
    typescript: "typescript",
    rust: "rust",
    go: "go",
    cpp: "cpp",
    c: "c",
    sql: "sql",
    bash: "bash",
    java: "java",
    ruby: "ruby",
    php: "php",
    swift: "swift",
    kotlin: "kotlin",
  };
  return map[language.toLowerCase()] || language;
}
